apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "db.fullname" . }}-pv
  labels:
    app: {{ include "db.name" . }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes: {{ .Values.storage.accessModes }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}
