apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.fullname" . }}-secret
type: Opaque
data:
  postgres-user: {{ .Values.postgresUser | b64enc }}
  postgres-password: {{ .Values.postgresPassword | b64enc }}
  postgres-database: {{ .Values.postgresDatabase | b64enc }}