apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: {{ include "db.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
  selector:
    app: {{ include "db.name" . }}